2025-10-01 20:32:23.644 - INFO[56] - supervisor cmd: /DATA/dev_area/jamong/manage_pack/supervisor-kit/svctl status

2025-10-01 20:32:23.644 - INFO[58] - <<<<<<<<<<<<<<<<<<<<<<<<<<<<<< [ SVCTL LIST ] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2025-10-01 20:32:23.644 - INFO[60] - ------------------------------------------------------------------------------
2025-10-01 20:32:23.644 - ERROR[90] - Traceback (most recent call last):
  File "check_service.py", line 61, in run
    total_cnt, check_cnt, err_cnt = c_svctl.check_status()
  File "/DATA/dev_area/jamong/manage_pack/manage_service/lib/control_svctl.py", line 103, in check_status
    self.log.error(traceback.format_exc())
NameError: global name 'traceback' is not defined

